// <auto-generated />
using System;
using Felino.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Felino.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328110920_UpdateCategorySeedData")]
    partial class UpdateCategorySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Felino.Api.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<bool>("OutdoorSeating")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Lunchpizza erbjudande",
                            Body = "Alla pizzor för 89 kr mellan 11–14!",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/campaigns/lunch.png",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Luncherbjudande"
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Familjepizza erbjudande",
                            Body = "2 pizzor + 2 dryck för endast 199 kr!",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/campaigns/family.png",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Familjepaket"
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Helgdeal burgare",
                            Body = "Valfri burgare + pommes + dryck för 129 kr!",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/campaigns/weekend.png",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Helgdeal"
                        },
                        new
                        {
                            Id = 4,
                            AltText = "Studentrabatt",
                            Body = "10% rabatt på hela menyn med studentkort.",
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/campaigns/student.png",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Studentrabatt"
                        });
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Klassiska pizzor med olika toppings.",
                            ImageUrl = "/images/admin/categories/pizzacategory.jpg",
                            Name = "Pizza",
                            Slug = "pizza"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hamburgare med klassiska och moderna tillbehör.",
                            ImageUrl = "/images/admin/categories/burgercategory.jpg",
                            Name = "Hamburgare",
                            Slug = "burger"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kebab, gyros och rullar serverade med fräscha tillbehör.",
                            ImageUrl = "/images/admin/categories/kebabcategory.jpg",
                            Name = "Kebab",
                            Slug = "kebab"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pastarätter med smakrika såser och klassiska recept.",
                            ImageUrl = "/images/admin/categories/pastacategory.jpg",
                            Name = "Pasta",
                            Slug = "pasta"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fräscha sallader med kyckling, ost, räkor och grönsaker.",
                            ImageUrl = "/images/admin/categories/salladcategory.jpg",
                            Name = "Sallader",
                            Slug = "sallad"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Grillrätter serverade med pommes och goda tillbehör.",
                            ImageUrl = "/images/admin/categories/grillcategory.jpg",
                            Name = "Grill",
                            Slug = "grill"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Pommes, såser och andra tillbehör som passar till maten.",
                            ImageUrl = "/images/admin/categories/tillbehorcategory.jpg",
                            Name = "Tillbehör",
                            Slug = "tillbehor"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Läsk, vatten och andra drycker till maten.",
                            ImageUrl = "/images/admin/categories/dryckcategory.jpg",
                            Name = "Dryck",
                            Slug = "dryck"
                        });
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Delivery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Extras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sauce")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Margherita pizza med ost",
                            CategoryId = 1,
                            ImageUrl = "/images/products/pizza-margherita.jpg",
                            Ingredients = "[\"ost\"]",
                            Name = "Margherita",
                            Price = 95.00m,
                            Slug = "margherita"
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Vesuvio pizza med skinka",
                            CategoryId = 1,
                            ImageUrl = "/images/products/pizza-vesuvio.jpg",
                            Ingredients = "[\"skinka\"]",
                            Name = "Vesuvio",
                            Price = 99.00m,
                            Slug = "vesuvio"
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Hawaii pizza med skinka och ananas",
                            CategoryId = 1,
                            ImageUrl = "/images/products/pizza-hawaii.jpg",
                            Ingredients = "[\"skinka\", \"ananas\"]",
                            Name = "Hawaii",
                            Price = 105.00m,
                            Slug = "hawaii"
                        },
                        new
                        {
                            Id = 4,
                            AltText = "La Bussola pizza med skinka och räkor",
                            CategoryId = 1,
                            ImageUrl = "/images/products/pizza-labussola.jpg",
                            Ingredients = "[\"skinka\", \"räkor\"]",
                            Name = "La Bussola",
                            Price = 115.00m,
                            Slug = "la-bussola"
                        },
                        new
                        {
                            Id = 5,
                            AltText = "Capricciosa pizza med skinka och champinjoner",
                            CategoryId = 1,
                            ImageUrl = "/images/products/pizza-capricciosa.jpg",
                            Ingredients = "[\"skinka\", \"champinjoner\"]",
                            Name = "Capricciosa",
                            Price = 105.00m,
                            Slug = "capricciosa"
                        },
                        new
                        {
                            Id = 6,
                            AltText = "Ciao Ciao pizza med oxfilé",
                            CategoryId = 1,
                            ImageUrl = "/images/products/pizza-ciaociao.jpg",
                            Ingredients = "[\"oxfilé\", \"tomat\", \"champinjoner\"]",
                            Name = "Ciao Ciao",
                            Price = 129.00m,
                            Sauce = "bearnaisesås",
                            Slug = "ciao-ciao"
                        },
                        new
                        {
                            Id = 7,
                            AltText = "Classic hamburgare",
                            CategoryId = 2,
                            ImageUrl = "/images/products/b-classic.jpg",
                            Ingredients = "[\"sallad\", \"tomat\", \"lök\", \"gurka\"]",
                            Name = "Classic",
                            Price = 95.00m,
                            Sauce = "dressing",
                            Slug = "classic"
                        },
                        new
                        {
                            Id = 8,
                            AltText = "Cheeseburgare",
                            CategoryId = 2,
                            ImageUrl = "/images/products/b-cheeseburgare.jpg",
                            Ingredients = "[\"ost\", \"sallad\", \"tomat\", \"gurka\"]",
                            Name = "Cheeseburgare",
                            Price = 99.00m,
                            Sauce = "dressing",
                            Slug = "cheeseburgare"
                        },
                        new
                        {
                            Id = 9,
                            AltText = "Ost & Bacon burgare",
                            CategoryId = 2,
                            ImageUrl = "/images/products/b-cheeseandbacon.jpg",
                            Ingredients = "[\"bacon\", \"ost\", \"sallad\", \"tomat\"]",
                            Name = "Ost & Bacon",
                            Price = 109.00m,
                            Sauce = "bbq-sås",
                            Slug = "ost-bacon"
                        },
                        new
                        {
                            Id = 10,
                            AltText = "Chili Jalapeño burgare",
                            CategoryId = 2,
                            ImageUrl = "/images/products/b-chilijalapeno.jpg",
                            Ingredients = "[\"ost\", \"jalapeños\", \"sallad\", \"tomat\"]",
                            Name = "Chili Jalapeño",
                            Price = 109.00m,
                            Sauce = "dressing",
                            Slug = "chili-jalapeno"
                        },
                        new
                        {
                            Id = 11,
                            AltText = "Kycklingburgare",
                            CategoryId = 2,
                            ImageUrl = "/images/products/b-kycklingburgare.jpg",
                            Ingredients = "[\"panerad kyckling\", \"sallad\", \"tomat\"]",
                            Name = "Kycklingburgare",
                            Price = 109.00m,
                            Sauce = "majonnäs",
                            Slug = "kycklingburgare"
                        },
                        new
                        {
                            Id = 12,
                            AltText = "Veggie burgare",
                            CategoryId = 2,
                            ImageUrl = "/images/products/b-veggie.jpg",
                            Ingredients = "[\"vegetarisk biff\", \"ost\", \"sallad\", \"tomat\"]",
                            Name = "Veggie",
                            Price = 105.00m,
                            Sauce = "dressing",
                            Slug = "veggie"
                        },
                        new
                        {
                            Id = 13,
                            AltText = "Kebabtallrik med pommes",
                            CategoryId = 3,
                            ImageUrl = "/images/products/k-kebabtallrik.jpg",
                            Ingredients = "[\"kebabkött\", \"pommes\", \"sallad\"]",
                            Name = "Kebabtallrik",
                            Price = 119.00m,
                            Slug = "kebabtallrik"
                        },
                        new
                        {
                            Id = 14,
                            AltText = "Kebabrulle",
                            CategoryId = 3,
                            ImageUrl = "/images/products/k-kebabrulle.jpg",
                            Ingredients = "[\"kebabkött\", \"sallad\", \"lök\", \"tomat\"]",
                            Name = "Kebabrulle",
                            Price = 109.00m,
                            Slug = "kebabrulle"
                        },
                        new
                        {
                            Id = 15,
                            AltText = "Kebab i bröd",
                            CategoryId = 3,
                            ImageUrl = "/images/products/k-kebabibrod.jpg",
                            Ingredients = "[\"kebabkött\", \"bröd\", \"sallad\"]",
                            Name = "Kebab i bröd",
                            Price = 99.00m,
                            Slug = "kebab-i-brod"
                        },
                        new
                        {
                            Id = 16,
                            AltText = "Kycklingrulle",
                            CategoryId = 3,
                            ImageUrl = "/images/products/k-kycklingrulle.jpg",
                            Ingredients = "[\"kyckling\", \"sallad\", \"lök\", \"tomat\"]",
                            Name = "Kycklingrulle",
                            Price = 109.00m,
                            Slug = "kycklingrulle"
                        },
                        new
                        {
                            Id = 17,
                            AltText = "Gyrostallrik med pommes",
                            CategoryId = 3,
                            ImageUrl = "/images/products/k-gyrostallrik.jpg",
                            Ingredients = "[\"gyros\", \"pommes\", \"sallad\"]",
                            Name = "Gyrostallrik",
                            Price = 119.00m,
                            Slug = "gyrostallrik"
                        },
                        new
                        {
                            Id = 18,
                            AltText = "Falafelrulle",
                            CategoryId = 3,
                            ImageUrl = "/images/products/k-falafelrulle.jpg",
                            Ingredients = "[\"falafel\", \"sallad\", \"lök\", \"tomat\"]",
                            Name = "Falafelrulle",
                            Price = 99.00m,
                            Slug = "falafelrulle"
                        },
                        new
                        {
                            Id = 19,
                            AltText = "Spaghetti Bolognese",
                            CategoryId = 4,
                            ImageUrl = "/images/products/p-spaghettibolognese.jpg",
                            Ingredients = "[\"köttfärssås\", \"tomat\", \"lök\", \"parmesan\"]",
                            Name = "Spaghetti Bolognese",
                            Price = 119.00m,
                            Slug = "spaghetti-bolognese"
                        },
                        new
                        {
                            Id = 20,
                            AltText = "Pasta Carbonara",
                            CategoryId = 4,
                            ImageUrl = "/images/products/p-carbonara.jpg",
                            Ingredients = "[\"bacon\", \"ägg\", \"grädde\", \"ost\"]",
                            Name = "Carbonara",
                            Price = 119.00m,
                            Slug = "carbonara"
                        },
                        new
                        {
                            Id = 21,
                            AltText = "Pasta Vegetariana",
                            CategoryId = 4,
                            ImageUrl = "/images/products/p-vegetariana.jpg",
                            Ingredients = "[\"svamp\", \"paprika\", \"lök\", \"tomat\"]",
                            Name = "Vegetariana",
                            Price = 109.00m,
                            Slug = "vegetariana"
                        },
                        new
                        {
                            Id = 22,
                            AltText = "Pasta Puttanesca",
                            CategoryId = 4,
                            ImageUrl = "/images/products/p-puttanesca.jpg",
                            Ingredients = "[\"tomat\", \"sardeller\", \"oliver\", \"kapris\", \"vitlök\"]",
                            Name = "Puttanesca",
                            Price = 115.00m,
                            Slug = "puttanesca"
                        },
                        new
                        {
                            Id = 23,
                            AltText = "Pasta Pollo",
                            CategoryId = 4,
                            ImageUrl = "/images/products/p-pastapollo.jpg",
                            Ingredients = "[\"kyckling\", \"grädde\", \"lök\", \"parmesan\"]",
                            Name = "Pasta Pollo",
                            Price = 129.00m,
                            Slug = "pasta-pollo"
                        },
                        new
                        {
                            Id = 24,
                            AltText = "Pasta Arrabbiata",
                            CategoryId = 4,
                            ImageUrl = "/images/products/p-arrabbiata.jpg",
                            Ingredients = "[\"tomat\", \"chili\", \"vitlök\", \"persilja\"]",
                            Name = "Arrabbiata",
                            Price = 109.00m,
                            Slug = "arrabbiata"
                        },
                        new
                        {
                            Id = 25,
                            AltText = "Grekisk Sallad",
                            CategoryId = 5,
                            ImageUrl = "/images/products/s-greeksalad.jpg",
                            Ingredients = "[\"sallad\", \"tomat\", \"gurka\", \"rödlök\", \"oliver\", \"fetaost\"]",
                            Name = "Grekisk Sallad",
                            Price = 109.00m,
                            Slug = "grekisk-sallad"
                        },
                        new
                        {
                            Id = 26,
                            AltText = "Kycklingsallad",
                            CategoryId = 5,
                            ImageUrl = "/images/products/s-chickensalad.jpg",
                            Ingredients = "[\"kyckling\", \"sallad\", \"tomat\", \"gurka\"]",
                            Name = "Kycklingsallad",
                            Price = 115.00m,
                            Slug = "kycklingsallad"
                        },
                        new
                        {
                            Id = 27,
                            AltText = "Räksallad",
                            CategoryId = 5,
                            ImageUrl = "/images/products/s-shrimpsalad.jpg",
                            Ingredients = "[\"räkor\", \"sallad\", \"ägg\", \"citron\", \"dill\"]",
                            Name = "Räksallad",
                            Price = 129.00m,
                            Slug = "raksallad"
                        },
                        new
                        {
                            Id = 28,
                            AltText = "Caprese Sallad",
                            CategoryId = 5,
                            ImageUrl = "/images/products/s-caprese.jpg",
                            Ingredients = "[\"tomat\", \"mozzarella\", \"basilika\", \"olivolja\", \"balsamico\"]",
                            Name = "Caprese",
                            Price = 109.00m,
                            Slug = "caprese"
                        },
                        new
                        {
                            Id = 29,
                            AltText = "Caesarsallad",
                            CategoryId = 5,
                            ImageUrl = "/images/products/s-caesarsalad.jpg",
                            Ingredients = "[\"romansallad\", \"kyckling\", \"krutonger\", \"parmesan\"]",
                            Name = "Caesarsallad",
                            Price = 125.00m,
                            Slug = "caesarsallad"
                        },
                        new
                        {
                            Id = 30,
                            AltText = "Halloumisallad",
                            CategoryId = 5,
                            ImageUrl = "/images/products/s-halloumisalad.jpg",
                            Ingredients = "[\"grillad halloumi\", \"sallad\", \"tomat\", \"gurka\", \"rödlök\"]",
                            Name = "Halloumisallad",
                            Price = 115.00m,
                            Slug = "halloumisallad"
                        },
                        new
                        {
                            Id = 31,
                            AltText = "Grillad fläskfilé med pommes",
                            CategoryId = 6,
                            ImageUrl = "/images/products/g-flaskfile.jpg",
                            Ingredients = "[\"fläskfilé\", \"pommes\"]",
                            Name = "Grillad Fläskfilé",
                            Price = 149.00m,
                            Slug = "grillad-flaskfile"
                        },
                        new
                        {
                            Id = 32,
                            AltText = "Grillad oxfilé med pommes",
                            CategoryId = 6,
                            ImageUrl = "/images/products/g-oxfile.jpg",
                            Ingredients = "[\"oxfilé\", \"pommes\"]",
                            Name = "Grillad Oxfilé",
                            Price = 189.00m,
                            Slug = "grillad-oxfile"
                        },
                        new
                        {
                            Id = 33,
                            AltText = "Grillad kyckling med pommes",
                            CategoryId = 6,
                            ImageUrl = "/images/products/g-kycklingfile.jpg",
                            Ingredients = "[\"kycklingfilé\", \"pommes\"]",
                            Name = "Grillad Kyckling",
                            Price = 139.00m,
                            Slug = "grillad-kyckling"
                        },
                        new
                        {
                            Id = 34,
                            AltText = "Mixed grill med pommes",
                            CategoryId = 6,
                            ImageUrl = "/images/products/g-mixedgrill.jpg",
                            Ingredients = "[\"oxfilé\", \"fläskfilé\", \"kycklingfilé\", \"pommes\"]",
                            Name = "Mixed Grill",
                            Price = 199.00m,
                            Slug = "mixed-grill"
                        },
                        new
                        {
                            Id = 35,
                            AltText = "Pommes frites",
                            CategoryId = 7,
                            ImageUrl = "/images/products/pommes.png",
                            Ingredients = "[\"pommes\"]",
                            Name = "Pommes Frites",
                            Price = 35.00m,
                            Slug = "pommes-frites"
                        },
                        new
                        {
                            Id = 36,
                            AltText = "Sötpotatispommes",
                            CategoryId = 7,
                            ImageUrl = "/images/products/sotpommes.png",
                            Ingredients = "[\"sötpotatispommes\"]",
                            Name = "Sötpotatispommes",
                            Price = 45.00m,
                            Slug = "sotpotatispommes"
                        },
                        new
                        {
                            Id = 37,
                            AltText = "Mozzarellasticks",
                            CategoryId = 7,
                            ImageUrl = "/images/products/mozzarella.png",
                            Ingredients = "[\"mozzarella\", \"panering\"]",
                            Name = "Mozzarellasticks",
                            Price = 49.00m,
                            Slug = "mozzarellasticks"
                        },
                        new
                        {
                            Id = 38,
                            AltText = "Lökringar",
                            CategoryId = 7,
                            ImageUrl = "/images/products/lokringar.png",
                            Ingredients = "[\"lök\", \"panering\"]",
                            Name = "Lökringar",
                            Price = 39.00m,
                            Slug = "lokringar"
                        },
                        new
                        {
                            Id = 39,
                            AltText = "Vitlöksbröd",
                            CategoryId = 7,
                            ImageUrl = "/images/products/vitloksbrod.png",
                            Ingredients = "[\"bröd\", \"vitlök\", \"smör\"]",
                            Name = "Vitlöksbröd",
                            Price = 35.00m,
                            Slug = "vitloksbrod"
                        },
                        new
                        {
                            Id = 40,
                            AltText = "Pizzasallad",
                            CategoryId = 7,
                            ImageUrl = "/images/products/pizzasallad.png",
                            Ingredients = "[\"vitkål\", \"olja\", \"vinäger\"]",
                            Name = "Pizzasallad",
                            Price = 25.00m,
                            Slug = "pizzasallad"
                        },
                        new
                        {
                            Id = 41,
                            AltText = "Coleslaw",
                            CategoryId = 7,
                            ImageUrl = "/images/products/coleslaw.png",
                            Ingredients = "[\"kål\", \"morot\", \"majonnäs\"]",
                            Name = "Coleslaw",
                            Price = 25.00m,
                            Slug = "coleslaw"
                        },
                        new
                        {
                            Id = 42,
                            AltText = "Bearnaisesås",
                            CategoryId = 7,
                            ImageUrl = "/images/products/bea.png",
                            Ingredients = "[\"bearnaisesås\"]",
                            Name = "Bearnaisesås",
                            Price = 20.00m,
                            Slug = "bearnaisesas"
                        },
                        new
                        {
                            Id = 43,
                            AltText = "Vitlökssås",
                            CategoryId = 7,
                            ImageUrl = "/images/products/vitloksas.png",
                            Ingredients = "[\"vitlökssås\"]",
                            Name = "Vitlökssås",
                            Price = 20.00m,
                            Slug = "vitlokssas"
                        },
                        new
                        {
                            Id = 44,
                            AltText = "Chilisås",
                            CategoryId = 7,
                            ImageUrl = "/images/products/chilisas.png",
                            Ingredients = "[\"chilisås\"]",
                            Name = "Chilisås",
                            Price = 20.00m,
                            Slug = "chilisas"
                        },
                        new
                        {
                            Id = 45,
                            AltText = "Cola Classic",
                            CategoryId = 8,
                            ImageUrl = "/images/products/cola-classic.png",
                            Ingredients = "[\"cola\"]",
                            Name = "Cola Classic",
                            Price = 20.00m,
                            Slug = "cola-classic"
                        },
                        new
                        {
                            Id = 46,
                            AltText = "Limonade Spritz",
                            CategoryId = 8,
                            ImageUrl = "/images/products/limonade-spritz.png",
                            Ingredients = "[\"citrus soda\"]",
                            Name = "Limonade Spritz",
                            Price = 20.00m,
                            Slug = "limonade-spritz"
                        },
                        new
                        {
                            Id = 47,
                            AltText = "Grape Sensation",
                            CategoryId = 8,
                            ImageUrl = "/images/products/grape-sensation.png",
                            Ingredients = "[\"grape soda\"]",
                            Name = "Grape Sensation",
                            Price = 20.00m,
                            Slug = "grape-sensation"
                        },
                        new
                        {
                            Id = 48,
                            AltText = "Tropical Punch",
                            CategoryId = 8,
                            ImageUrl = "/images/products/tropical-punch.png",
                            Ingredients = "[\"tropical soda\"]",
                            Name = "Tropical Punch",
                            Price = 20.00m,
                            Slug = "tropical-punch"
                        },
                        new
                        {
                            Id = 49,
                            AltText = "Dr. Cherry",
                            CategoryId = 8,
                            ImageUrl = "/images/products/dr-cherry.png",
                            Ingredients = "[\"cherry cola\"]",
                            Name = "Dr. Cherry",
                            Price = 20.00m,
                            Slug = "dr-cherry"
                        },
                        new
                        {
                            Id = 50,
                            AltText = "Root Beer Tradition",
                            CategoryId = 8,
                            ImageUrl = "/images/products/root-beer.png",
                            Ingredients = "[\"root beer\"]",
                            Name = "Root Beer Tradition",
                            Price = 20.00m,
                            Slug = "root-beer-tradition"
                        },
                        new
                        {
                            Id = 51,
                            AltText = "Cream Soda Delight",
                            CategoryId = 8,
                            ImageUrl = "/images/products/cream-soda.png",
                            Ingredients = "[\"cream soda\"]",
                            Name = "Cream Soda Delight",
                            Price = 20.00m,
                            Slug = "cream-soda-delight"
                        },
                        new
                        {
                            Id = 52,
                            AltText = "Lemon Tea Refresh",
                            CategoryId = 8,
                            ImageUrl = "/images/products/lemon-tea.png",
                            Ingredients = "[\"lemon iced tea\"]",
                            Name = "Lemon Tea Refresh",
                            Price = 20.00m,
                            Slug = "lemon-tea-refresh"
                        },
                        new
                        {
                            Id = 53,
                            AltText = "Ginger Ale Extra",
                            CategoryId = 8,
                            ImageUrl = "/images/products/ginger-ale.png",
                            Ingredients = "[\"ginger ale\"]",
                            Name = "Ginger Ale Extra",
                            Price = 20.00m,
                            Slug = "ginger-ale-extra"
                        },
                        new
                        {
                            Id = 54,
                            AltText = "Orange Burst",
                            CategoryId = 8,
                            ImageUrl = "/images/products/orange-burst.png",
                            Ingredients = "[\"orange soda\"]",
                            Name = "Orange Burst",
                            Price = 20.00m,
                            Slug = "orange-burst"
                        });
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Admin");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Felino.Api.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felino.Api.Domain.Entities.Table", "Table")
                        .WithMany("Bookings")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Felino.Api.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Felino.Api.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Felino.Api.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Felino.Api.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Product", b =>
                {
                    b.HasOne("Felino.Api.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Felino.Api.Domain.Entities.Table", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
